[project]
name = "video-editing-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agentuity>=0.0.83",
    "click>=8.1.8",
    "instructor[anthropic]>=0.6.7",
    "pydantic-ai[logfire,mcp]>=0.2.6",
    "videojungle>=0.1.64",
    "yt-dlp[curl-cffi,default]>=2025.5.22",
]

[dependency-groups]
dev = [
    "ipython>=9.2.0",
]
